language: scala
scala:
  - 2.12.10
jdk:
  - openjdk10
script: 
  - sbt ++$TRAVIS_SCALA_VERSION clean compile flowLintLib test doc
  # Tricks to avoid unnecessary cache updates
  - find $HOME/.sbt -name "*.lock" | xargs rm -f
  - find $HOME/.ivy2 -name "ivydata-*.properties" | xargs rm -f
branches:
  only:
    - master
